const $=s=>document.querySelector(s), STORAGE='recipe-finder-saved-v2';
let servings=2, saved=loadSaved(), messages=[];
const cuisines=[['Indian','🍛'],['Italian','🍝'],['Chinese','🥡'],['Mexican','🌮'],['Japanese','🍣'],['Thai','🍜']];
const starters=['I have potatoes, onions and tomatoes','A quick paneer dinner','Something comforting with rice'];
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{return[]}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(saved));renderSaved()}
function escapeHtml(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function md(x){return escapeHtml(x).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h3>$1</h3>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/^[-•] (.*)$/gm,'<li>$1</li>').replace(/^(\d+)\. (.*)$/gm,'<li>$2</li>').replace(/\n\n/g,'<br><br>').replace(/\n/g,'<br>')}
function parseMeta(text){const m=text.match(/<!--RECIPE_META\s+({.*?})-->/s);if(!m)return null;try{return JSON.parse(m[1])}catch{return null}}
function clean(text){return text.replace(/<!--RECIPE_META\s+({.*?})-->/s,'').trim()}
function recipeCard(text, id){const meta=parseMeta(text); const body=clean(text); if(!meta)return md(body); const name=meta.recipeName||meta.name||'Recipe'; const item={...meta,recipeName:name,emoji:meta.emoji||'🍽️',cuisine:meta.cuisine||'Global',servedFor:Number(meta.servedFor||servings),body,createdAt:new Date().toISOString()}; const isSaved=saved.some(s=>s.recipeName.toLowerCase()===name.toLowerCase()); return `<div class="recipe"><h3>${escapeHtml(name)}</h3><div class="meta"><span class="tag">${escapeHtml(item.emoji)} ${escapeHtml(item.cuisine)}</span><span class="tag">👥 ${item.servedFor} people</span></div>${md(body)}<div class="recipe-actions"><button class="action primary" data-save='${escapeHtml(JSON.stringify(item))}'>${isSaved?'✓ Saved':'♡ Save Recipe'}</button><button class="action" data-copy='${escapeHtml(body)}'>Copy Recipe</button></div></div>`}
function render(){const root=$('#app');root.innerHTML=`<div class="app"><header class="topbar"><a class="brand" href="./"><span class="brand-mark">🍳</span><span><strong>Recipe Finder</strong><em>PRO</em></span></a><div class="topnote">Quick ideas · Exact quantities · Zero guesswork</div></header><div class="workspace"><section class="chat"><section class="hero"><div><span class="eyebrow">Your clever kitchen companion</span><h1>What’s cooking<br>in your kitchen?</h1><p>Tell me a cuisine, dish, or the ingredients you have. Recipes are scaled for your table and can be saved on this device.</p></div><div class="plate-art">🍅 🌿 🍛</div></section><section class="quick"><span class="section-label">Explore a cuisine</span><div class="cuisine-grid">${cuisines.map(([n,e])=>`<button class="chip" data-prompt="I am craving ${n} cuisine"><span>${e}</span>${n}</button>`).join('')}</div><div class="starter-row">${starters.map(x=>`<button class="starter" data-prompt="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('')}</div></section><div class="messages" id="messages"></div><div class="composer-wrap"><div id="error"></div><div class="serving"><span>👥 <b>How many people?</b> Quantities scale automatically.</span><div class="serving-controls">${[1,2,4,6].map(n=>`<button class="serv ${servings===n?'active':''}" data-serv="${n}">${n}</button>`).join('')}<input id="custom" type="number" min="1" max="20" value="${servings}"></div></div><form class="composer" id="form"><textarea id="input" rows="2" placeholder="Tell me a cuisine, dish, or the ingredients you have…"></textarea><button class="send" id="send" aria-label="Find a recipe">➤</button></form><div class="hint">Press Enter to cook · Shift + Enter for a new line</div></div></section><aside class="side"><div class="side-head"><div><small>Your kitchen journal</small><h2>Saved Recipes</h2></div><span>📖</span></div><div class="saved-list" id="saved"></div></aside></div></div>`;
$('#form').addEventListener('submit',e=>{e.preventDefault();ask($('#input').value)});$('#input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask($('#input').value)}});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#input').value=b.dataset.prompt;$('#input').focus()});document.querySelectorAll('[data-serv]').forEach(b=>b.onclick=()=>setServ(Number(b.dataset.serv)));$('#custom').onchange=e=>setServ(Math.min(20,Math.max(1,Number(e.target.value)||1)));renderSaved();
}
function setServ(n){servings=Math.min(20,Math.max(1,n));document.querySelector('#custom').value=servings;document.querySelectorAll('.serv').forEach(b=>b.classList.toggle('active',Number(b.dataset.serv)===servings))}
function addMessage(role,text){messages.push({role,text,id:crypto.randomUUID?.()||String(Date.now())});drawMessages()}
function drawMessages(){const box=$('#messages');box.innerHTML=messages.map(m=>`<article class="message ${m.role}"><div class="avatar">${m.role==='assistant'?'🍳':'YOU'}</div><div class="bubble"><div class="label">${m.role==='assistant'?'Recipe Finder Pro':'Your request'}</div>${m.role==='assistant'?recipeCard(m.text,m.id):md(m.text)}</div></article>`).join('');box.scrollTop=box.scrollHeight;box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveRecipe(JSON.parse(b.dataset.save)));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard?.writeText(b.dataset.copy);b.textContent='✓ Copied'});}
function renderSaved(){const box=$('#saved');if(!box)return;if(!saved.length){box.innerHTML='<div class="empty">No saved recipes yet.<br>Tap <b>Save Recipe</b> after a recipe is generated.</div>';return}box.innerHTML=saved.map((r,i)=>`<div class="saved-card"><span class="emoji">${escapeHtml(r.emoji||'🍽️')}</span><div><strong>${escapeHtml(r.recipeName)}</strong><small>${escapeHtml(r.cuisine||'Global')} · ${r.servedFor||servings} people</small></div><div class="saved-actions"><button class="icon-btn" title="Open" data-open="${i}">↗</button><button class="icon-btn" title="Delete" data-del="${i}">×</button></div></div>`).join('');box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saved.splice(Number(b.dataset.del),1);persist();drawMessages()});box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const r=saved[Number(b.dataset.open)];addMessage('assistant',`<!--RECIPE_META ${JSON.stringify(r)}-->\n${r.body}`);window.scrollTo({top:0,behavior:'smooth'})})}
function saveRecipe(r){if(!r?.recipeName)return;const exists=saved.some(x=>x.recipeName.toLowerCase()===r.recipeName.toLowerCase());if(!exists){saved.unshift({...r,savedAt:new Date().toISOString()});saved=saved.slice(0,50);persist();drawMessages()}}
function localRecipe(text){
  const q=text.toLowerCase();
  let name='Quick Mixed Vegetable Masala', emoji='🥘', cuisine='Indian';
  let ingredients=['2 tbsp oil','1 onion, chopped','2 tomatoes, chopped','1 tsp ginger-garlic paste','1 tsp cumin','1/2 tsp turmeric','1 tsp chilli powder','1 tsp coriander powder','2 cups mixed vegetables','Salt to taste','1/2 cup water','Fresh coriander'];
  let steps=['Heat oil and add cumin.','Add onion and cook until lightly golden.','Add ginger-garlic paste and tomatoes; cook until soft.','Add spices and mixed vegetables. Stir well.','Add water, cover and cook until the vegetables are tender.','Finish with fresh coriander and serve hot.'];
  if(q.includes('paneer')){name='Easy Paneer Masala';emoji='🧀';cuisine='Indian';ingredients=['250 g paneer','1 onion, chopped','2 tomatoes, pureed','1 tbsp oil','1 tsp ginger-garlic paste','1/2 tsp turmeric','1 tsp chilli powder','1 tsp garam masala','1/2 cup water','2 tbsp cream or yogurt','Salt to taste','Fresh coriander'];steps=['Heat oil and sauté onion until golden.','Add ginger-garlic paste and tomato puree. Cook until oil separates.','Add turmeric, chilli powder, salt and water. Simmer 3 minutes.','Add paneer and garam masala. Cook gently for 4–5 minutes.','Stir in cream or yogurt and garnish with coriander.'];}
  else if(q.includes('rice')||q.includes('biryani')){name=q.includes('biryani')?'Quick Veg Biryani':'Easy Vegetable Rice';emoji='🍚';cuisine='Indian';ingredients=['1 cup basmati rice','1.5 cups water','1 cup mixed vegetables','1 onion, sliced','1 tbsp oil or ghee','1/2 tsp cumin','1/2 tsp turmeric','1 tsp garam masala','Salt to taste','2 tbsp coriander','Lemon wedge'];steps=['Rinse rice well.','Heat oil and sauté cumin and onion.','Add vegetables and spices; cook 2 minutes.','Add rice, water and salt. Cover and simmer until rice is tender.','Rest 5 minutes, fluff and finish with coriander and lemon.'];}
  else if(q.includes('italian')||q.includes('pasta')){name='Creamy Tomato Pasta';emoji='🍝';cuisine='Italian';ingredients=['180 g pasta','1 tbsp olive oil','2 garlic cloves, minced','1 cup tomato puree','1/2 tsp chilli flakes','1/2 tsp Italian herbs','1/3 cup cream','30 g grated cheese','Salt and pepper'];steps=['Boil pasta until al dente and reserve 1/2 cup pasta water.','Sauté garlic in olive oil.','Add tomato puree, herbs, chilli and seasoning; simmer 5 minutes.','Stir in cream and cheese.','Toss with pasta, adding a splash of pasta water if needed.'];}
  else if(q.includes('chinese')){name='Easy Vegetable Stir-Fry';emoji='🥡';cuisine='Chinese';ingredients=['2 cups mixed vegetables','1 tbsp oil','2 garlic cloves, minced','1 tsp grated ginger','1 tbsp soy sauce','1 tsp vinegar','1 tsp honey or sugar','1/2 tsp chilli sauce','2 tbsp water','Salt to taste'];steps=['Heat a pan or wok until hot.','Add oil, garlic and ginger. Stir for 20 seconds.','Add vegetables and stir-fry on high heat for 3–4 minutes.','Add soy sauce, vinegar, honey and chilli sauce.','Toss for 1 minute and serve immediately.'];}
  else if(q.includes('mexican')){name='Easy Mexican Bean Tacos';emoji='🌮';cuisine='Mexican';ingredients=['6 taco shells','1 cup cooked kidney or black beans','1/2 onion, diced','1 tomato, diced','1/2 tsp cumin','1/2 tsp chilli powder','1/2 cup grated cheese','Lettuce','Lime wedges','Salt to taste'];steps=['Warm the beans with onion, cumin, chilli and salt.','Heat taco shells according to the package.','Fill shells with beans, tomato, lettuce and cheese.','Finish with lime and serve.'];}
  const scale=servings/2;
  const scaled=ingredients.map(x=>x.replace(/^(\d+(?:\.\d+)?)\s*(tbsp|tsp|g|kg|ml|cup|cups|pieces?)/i,(m,n,u)=>`${Math.round((+n*scale)*10)/10} ${u}`));
  return `<!--RECIPE_META ${JSON.stringify({recipeName:name,emoji,cuisine,servedFor:servings})}-->\n**${name}**\n\n**Ingredients (${servings} people)**\n${scaled.map(x=>'- '+x).join('\n')}\n\n**Method**\n${steps.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n*Tip: Adjust salt and chilli to taste.*`;
}

async function ask(value){const text=value.trim();if(!text)return;const send=$('#send'),input=$('#input');send.disabled=true;input.disabled=true;$('#error').innerHTML='';addMessage('user',text);const typing=document.createElement('div');typing.className='message assistant';typing.innerHTML='<div class="avatar">🍳</div><div class="bubble"><div class="typing"><i></i><i></i><i></i> Creating your recipe…</div></div>';$('#messages').appendChild(typing);try{let answer='';
    const canUseNetlify=location.hostname.endsWith('.netlify.app')||location.hostname==='localhost'||location.hostname==='127.0.0.1';
    if(canUseNetlify){
      try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...messages.filter(m=>m.role!=='assistant'||m.text),{role:'user',content:text}],sessionId:getSession(),servings})});if(res.ok){const data=await res.json();answer=data.text||data.content||'';}}
      catch(e){/* use local fallback */}
    }
    if(!answer) answer=localRecipe(text);
    typing.remove();addMessage('assistant',answer);
  }catch(err){typing.remove();$('#error').innerHTML=`<div class="error">${escapeHtml(err.message||'Could not generate a recipe.')} Please try again.</div>`}finally{send.disabled=false;input.disabled=false;input.focus()}}

function getSession(){let x=localStorage.getItem('recipe-finder-session-id');if(!x){x=crypto.randomUUID?.()||String(Date.now());localStorage.setItem('recipe-finder-session-id',x)}return x}
render();
