const $=s=>document.querySelector(s), STORAGE='recipe-finder-saved-v2';
let servings=2, saved=loadSaved(), messages=[];
const cuisines=[['Indian','🍛'],['Italian','🍝'],['Chinese','🥡'],['Mexican','🌮'],['Japanese','🍣'],['Thai','🍜']];
const starters=['I have potatoes, onions and tomatoes','A quick paneer dinner','Something comforting with rice'];
function loadSaved(){try{return JSON.parse(localStorage.getItem(STORAGE)||'[]')}catch{return[]}}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(saved));renderSaved()}
function escapeHtml(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function md(x){return escapeHtml(x).replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h3>$1</h3>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/^[-•] (.*)$/gm,'<li>$1</li>').replace(/^(\d+)\. (.*)$/gm,'<li>$2</li>').replace(/\n\n/g,'<br><br>').replace(/\n/g,'<br>')}
function parseMeta(text){const m=text.match(/<!--RECIPE_META\s+({.*?})-->/s);if(!m)return null;try{return JSON.parse(m[1])}catch{return null}}
function clean(text){return text.replace(/<!--RECIPE_META\s+({.*?})-->/s,'').trim()}
function recipeCard(text, id){const meta=parseMeta(text); const body=clean(text); if(!meta)return md(body); const name=meta.recipeName||meta.name||'Recipe'; const item={...meta,recipeName:name,emoji:meta.emoji||'🍽️',cuisine:meta.cuisine||'Global',servedFor:Number(meta.servedFor||servings),body,createdAt:new Date().toISOString()}; const isSaved=saved.some(s=>s.recipeName.toLowerCase()===name.toLowerCase()); return `<div class="recipe"><h3>${escapeHtml(name)}</h3><div class="meta"><span class="tag">${escapeHtml(item.emoji)} ${escapeHtml(item.cuisine)}</span><span class="tag">👥 ${item.servedFor} people</span></div>${md(body)}<div class="recipe-actions"><button class="action primary" data-save='${escapeHtml(JSON.stringify(item))}'>${isSaved?'✓ Saved':'♡ Save Recipe'}</button><button class="action" data-copy='${escapeHtml(body)}'>Copy Recipe</button></div></div>`}
function render(){const root=$('#app');root.innerHTML=`<div class="app"><header class="topbar"><a class="brand" href="/"><span class="brand-mark">🍳</span><span><strong>Recipe Finder</strong><em>PRO</em></span></a><div class="topnote">Quick ideas · Exact quantities · Zero guesswork</div></header><div class="workspace"><section class="chat"><section class="hero"><div><span class="eyebrow">Your clever kitchen companion</span><h1>What’s cooking<br>in your kitchen?</h1><p>Tell me a cuisine, dish, or the ingredients you have. Recipes are scaled for your table and can be saved on this device.</p></div><div class="plate-art">🍅 🌿 🍛</div></section><section class="quick"><span class="section-label">Explore a cuisine</span><div class="cuisine-grid">${cuisines.map(([n,e])=>`<button class="chip" data-prompt="I am craving ${n} cuisine"><span>${e}</span>${n}</button>`).join('')}</div><div class="starter-row">${starters.map(x=>`<button class="starter" data-prompt="${escapeHtml(x)}">${escapeHtml(x)}</button>`).join('')}</div></section><div class="messages" id="messages"></div><div class="composer-wrap"><div id="error"></div><div class="serving"><span>👥 <b>How many people?</b> Quantities scale automatically.</span><div class="serving-controls">${[1,2,4,6].map(n=>`<button class="serv ${servings===n?'active':''}" data-serv="${n}">${n}</button>`).join('')}<input id="custom" type="number" min="1" max="20" value="${servings}"></div></div><form class="composer" id="form"><textarea id="input" rows="2" placeholder="Tell me a cuisine, dish, or the ingredients you have…"></textarea><button class="send" id="send" aria-label="Find a recipe">➤</button></form><div class="hint">Press Enter to cook · Shift + Enter for a new line</div></div></section><aside class="side"><div class="side-head"><div><small>Your kitchen journal</small><h2>Saved Recipes</h2></div><span>📖</span></div><div class="saved-list" id="saved"></div></aside></div></div>`;
$('#form').addEventListener('submit',e=>{e.preventDefault();ask($('#input').value)});$('#input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask($('#input').value)}});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#input').value=b.dataset.prompt;$('#input').focus()});document.querySelectorAll('[data-serv]').forEach(b=>b.onclick=()=>setServ(Number(b.dataset.serv)));$('#custom').onchange=e=>setServ(Math.min(20,Math.max(1,Number(e.target.value)||1)));renderSaved();
}
function setServ(n){servings=Math.min(20,Math.max(1,n));document.querySelector('#custom').value=servings;document.querySelectorAll('.serv').forEach(b=>b.classList.toggle('active',Number(b.dataset.serv)===servings))}
function addMessage(role,text){messages.push({role,text,id:crypto.randomUUID?.()||String(Date.now())});drawMessages()}
function drawMessages(){const box=$('#messages');box.innerHTML=messages.map(m=>`<article class="message ${m.role}"><div class="avatar">${m.role==='assistant'?'🍳':'YOU'}</div><div class="bubble"><div class="label">${m.role==='assistant'?'Recipe Finder Pro':'Your request'}</div>${m.role==='assistant'?recipeCard(m.text,m.id):md(m.text)}</div></article>`).join('');box.scrollTop=box.scrollHeight;box.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveRecipe(JSON.parse(b.dataset.save)));box.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard?.writeText(b.dataset.copy);b.textContent='✓ Copied'});}
function renderSaved(){const box=$('#saved');if(!box)return;if(!saved.length){box.innerHTML='<div class="empty">No saved recipes yet.<br>Tap <b>Save Recipe</b> after a recipe is generated.</div>';return}box.innerHTML=saved.map((r,i)=>`<div class="saved-card"><span class="emoji">${escapeHtml(r.emoji||'🍽️')}</span><div><strong>${escapeHtml(r.recipeName)}</strong><small>${escapeHtml(r.cuisine||'Global')} · ${r.servedFor||servings} people</small></div><div class="saved-actions"><button class="icon-btn" title="Open" data-open="${i}">↗</button><button class="icon-btn" title="Delete" data-del="${i}">×</button></div></div>`).join('');box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{saved.splice(Number(b.dataset.del),1);persist();drawMessages()});box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const r=saved[Number(b.dataset.open)];addMessage('assistant',`<!--RECIPE_META ${JSON.stringify(r)}-->\n${r.body}`);window.scrollTo({top:0,behavior:'smooth'})})}
function saveRecipe(r){if(!r?.recipeName)return;const exists=saved.some(x=>x.recipeName.toLowerCase()===r.recipeName.toLowerCase());if(!exists){saved.unshift({...r,savedAt:new Date().toISOString()});saved=saved.slice(0,50);persist();drawMessages()}}
async function ask(value){const text=value.trim();if(!text)return;const send=$('#send'),input=$('#input');send.disabled=true;input.disabled=true;$('#error').innerHTML='';addMessage('user',text);const typing=document.createElement('div');typing.className='message assistant';typing.innerHTML='<div class="avatar">🍳</div><div class="bubble"><div class="typing"><i></i><i></i><i></i> Balancing spices and scaling every quantity…</div></div>';$('#messages').appendChild(typing);try{const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...messages.filter(m=>m.role!=='assistant'||m.text),{role:'user',content:text}],sessionId:getSession(),servings})});if(!res.ok)throw new Error(`Recipe service returned ${res.status}`);const contentType=res.headers.get('content-type')||'';let answer='';if(contentType.includes('text/event-stream')){const reader=res.body.getReader(),decoder=new TextDecoder();let buf='';for(;;){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const parts=buf.split('\n');buf=parts.pop()||'';for(const line of parts){if(!line.startsWith('data:'))continue;const raw=line.slice(5).trim();if(raw==='[DONE]')continue;try{const ev=JSON.parse(raw);if(ev.type==='TEXT_MESSAGE_CONTENT')answer+=ev.delta||ev.content||''}catch{}}}}else{const data=await res.json();answer=data.text||data.content||''}if(!answer)throw new Error('Empty recipe response');typing.remove();addMessage('assistant',answer)}catch(err){typing.remove();$('#error').innerHTML=`<div class="error">${escapeHtml(err.message||'Could not generate a recipe.')} Try again, or check that your AI API key is configured on Netlify.</div>`}finally{send.disabled=false;input.disabled=false;input.focus()}}
function getSession(){let x=localStorage.getItem('recipe-finder-session-id');if(!x){x=crypto.randomUUID?.()||String(Date.now());localStorage.setItem('recipe-finder-session-id',x)}return x}
render();
